### ISSUE TITLE
The I.T. Manager Tool Box

### ISSUE THREAD

**Issue by sebaminguez** [IT-Floss/Third-Tuesday-Talks#3]
Se estarán abordando herramientas que facilitan y potencian La gestión de T.I.

Incluyendo una breve introducción a cada una y casos de éxito en su implementación.

**Comment by sebaminguez** [comment]
Un lujo escuchar las experiencias de Ismael, Lucas y Jorge.
Diapositivas disponibles en https://goo.gl/emmiE1
Pueden revivir ele vento completo en nuestra web http://itfloss.rocks/#ttt

**Comment by julianbutti** [comment]
Muy buena la charla
